#!/usr/bin/env python3

import sys
import os

from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import cprint

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile word")

    # get tweets
    tweets = get_user_timeline(sys.argv[1])

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze each tweet and print
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score < 0:
            cprint(str(score) + ", " + tweet, "red", end="\n")
        if score > 0:
            cprint(" " + str(score) + ", " + tweet, "green", end="\n")
        if score == 0:
            cprint(" " + str(score) + ", " + tweet, "yellow", end="\n")
    return

if __name__ == "__main__":
    main()
